### ISSUE TITLE
Does not work on Multisite install

### ISSUE THREAD

**Issue by blobaugh** [gyrus/Force-Strong-Passwords#2]
I just changed a user's password to 'weak' from the Network Admin > Users profile page. I receive no warning and the password was successfully updated to 'weak'. There must be more hooks for Multisite versus Single install

**Comment by gyrus** [comment]
For anyone interested in multisite support, I've just accepted a pull request from @dpiquet which enforces strong passwords on network admin screens. Please test the latest version here on GitHub and post any queries / issues.

**Comment by carstingaxion** [comment]
Seems to work fine on `wp-admin/network/user-edit.php`. Thanks @dpiquet & @gyrus !

**Comment by gyrus** [comment]
The fix for multisite has been released on wordpress.org. I'm closing this issue, but please notify me if any problems are noticed!
